# Generated by Django 5.0.6 on 2025-06-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YieldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_yield', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('forecast_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast.forecastmodel')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.plot')),
            ],
        ),
    ]
