# Generated by Django 5.0.6 on 2025-06-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inspector', models.CharField(max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.plot')),
            ],
        ),
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualityinspection')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualityparameter')),
            ],
        ),
    ]
